### ISSUE TITLE
pm2 show logrotate errored on Windows Server 2012 x64, Node v4.1.1

### ISSUE THREAD

**Issue by micksatana** [pm2-hive/pm2-logrotate#12]
<b>Environment:</b>
Windows Server 2012 x64, Node 4.1.1
pm2 is fresh installed
logrotate is fresh installed
No other app running

When run "pm2 show logrotate" will see the status "errored". In the log file of logrotate has the following error around 15 times.

<pre>
<code>
Error: <files> required
    at Object.<anonymous> (C:\Users\mick\.pm2\node_modules\logrotate\bin\rotate:38:26)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function._load (C:\Users\mick\AppData\Roaming\npm\node_modules\pm2\node_modules\pmx\lib\transaction.js:62:21)
    at Object.<anonymous> (C:\Users\mick\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:28:21)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
</code>
</pre>

**Comment by bragma** [comment]
Is this issue really about this module? The name is not the same (i.e. 'logrotate' vs 'pm2-logrotate') and the stack trace refers to files that do not seem to belong to this...

**Comment by micksatana** [comment]
My apologies. I think it's my silly mistake when playing around which pm2 and pm2-logrotate. I probably confuse and npm install manually on the package. Now, I retry and work perfectly fine.
