### ISSUE TITLE
logrotate errors out on startup 

### ISSUE THREAD

**Issue by aeisenberg** [pm2-hive/pm2-logrotate#30]
When I restart pm2, I get the following error from pm2-logrotate. This prevents the apps from starting.

```
TypeError: Cannot read property 'toString' of undefined
    at get_limit_size (/home/jenkins/.pm2/node_modules/pm2-logrotate/app.js:49:36)
    at Object.<anonymous> (/home/jenkins/.pm2/node_modules/pm2-logrotate/app.js:30:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function._load (/home/jenkins/.pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Object.<anonymous> (/home/jenkins/.pm2/node_modules/pm2/lib/ProcessContainerFork.js:46:21)
    at Module._compile (module.js:541:32)
```

I was able to install pm2-logrotate and successfully run it for a while, but I am prevented from using it after restarting. 

I added the following to my module_conf.json and it looks like by explicitly adding the variables, I am able to use pm2-logrotate again:

```
    "pm2-logrotate": {
        "interval": "1",
        "max_size": "10M",
        "interval_unit": "DD",
        "retain": "4"
    }
```

However, this is of couse less than ideal. Any ideas on why this is happening?

**Comment by vmarchaud** [comment]
Fixed in latest update (v2.0.0).
