### ISSUE TITLE
Bad "this" reference when notifying of file error.  (this._interpretError is not a function)

### ISSUE THREAD

**Issue by dangerbacon** [pm2-hive/pm2-logrotate#41]
logrotate encountered a file permissions issue (could not rotate the file).

    TypeError: this._interpretError is not a function
        at WriteStream.Notify.notify (/home/pm2user/.pm2/node_modules/pmx/lib/notify.js:106:22)
        at emitOne (events.js:101:20)
        at WriteStream.emit (events.js:188:7)
        at WriteStream.<anonymous> (fs.js:2109:12)
        at FSReqWrap.oncomplete (fs.js:123:15)

This is because of this fragment of code:

    Notify.notify = function(err) {

      var ret_err = this._interpretError(err);

When called, "this" is not a Notify object.  I believe this is caused by these lines in logrotate app.js:

      // listen for error
            readStream.on('error', pmx.notify);
      writeStream.on('error', pmx.notify);
      if (COMPRESSION)
        GZIP.on('error', pmx.notify);

When these encounter errors, they call the right function, but the "this" reference is incorrect.

I believe you can fix it by doing something like this:

      // listen for error
            readStream.on('error', pmx.notify.bind(pmx));
      writeStream.on('error', pmx.notify.bind(pmx));
      if (COMPRESSION)
        GZIP.on('error', pmx.notify.bind(pmx));

The "bind" will cause these events to call the notify function with the pmx object as the "this" reference.

**Comment by farin99** [comment]
Any updates on this issue? I'm seeing this error when using node 7.8
