### ISSUE TITLE
Regression: Logrotate failing as of 2.2.2

### ISSUE THREAD

**Issue by jglancy** [pm2-hive/pm2-logrotate#68]
Related to this commit: https://github.com/pm2-hive/pm2-logrotate/commit/9395a3b296f756c666b89ca6226622152563c553

```
TypeError: Cannot read property 'close' of undefined
    at ReadStream.<anonymous> (/home/morph/.pm2/node_modules/pm2-logrotate/app.js:117:9)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

This is causing the log rotate to fail, which means instances are running out of disk space and becoming useless.

**Comment by vmarchaud** [comment]
Will publish a fix
