### ISSUE TITLE
Benefits of pm2-logrotate over standard logrotate?

### ISSUE THREAD

**Issue by nitrocode** [pm2-hive/pm2-logrotate#79]
Recently hit an issue where our hourly rolled over compressed logs sometimes contain data for the next hour due to a timing issue or some kind of delay.

We haven't explored the option but we were thinking about trying the standard `logrotate` ([which you have kindly documented on your site](http://pm2.keymetrics.io/docs/usage/log-management/#setting-up-a-native-logrotate)) to see if we can get more accurate results.

Is there a feature in `pm2-logrotate` that doesn't exist in `logrotate`? If so, then we may try to fix this issue and submit a PR.

**Comment by vmarchaud** [comment]
logrotate is a native script available on most linux distribs, see https://linux.die.net/man/8/logrotate.
I would personally recommend to configure a native solution since its more performant and generally have more feature . We only made the module for people wanting one command install & automatic configuration of log rotation

**Comment by pankleks** [comment]
pm2-logrotate works on windows too

**Comment by AriesLian** [comment]
it doesn't on my mac book pro 15''. after i set the max_size 1K, Here comes the error:
`TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function
    at _addListener (events.js:180:11)
    at WriteStream.addListener (events.js:240:10)
    at WriteStream.close (fs.js:2298:10)
    at WriteStream.<anonymous> (/Users/AriesLian/.pm2/modules/pm2-logrotate/node_modules/pm2-logrotate/app.js:138:17)
    at WriteStream.emit (events.js:164:20)
    at finishMaybe (_stream_writable.js:616:14)
    at endWritable (_stream_writable.js:624:3)
    at WriteStream.Writable.end (_stream_writable.js:575:5)
    at ReadStream.onend (_stream_readable.js:598:10)
    at Object.onceWrapper (events.js:254:19)`
