### ISSUE TITLE
Getting zlib binding closed error

### ISSUE THREAD

**Issue by pankleks** [pm2-hive/pm2-logrotate#80]
I'm getting errors like `zlib binding closed`

Stack trace:
```
Error: zlib binding closed
at Gzip._transform (zlib.js:370:15)
at Gzip._flush (zlib.js:302:8)
at Gzip.prefinish (_stream_transform.js:137:10)
at emitNone (events.js:106:13)
at Gzip.emit (events.js:208:7)
at prefinish (_stream_writable.js:593:14)
at finishMaybe (_stream_writable.js:601:5)
at afterWrite (_stream_writable.js:455:3)
at onwrite (_stream_writable.js:445:7)
at Gzip.afterTransform (_stream_transform.js:90:3)
```

v: 2.3.0
pm2: 2.7.2

**Comment by pankleks** [comment]
I think 2.4.0 fixes the issue, thanks
