### ISSUE TITLE
TypeError: WATCHED_FILES.includes is not a function

### ISSUE THREAD

**Issue by mmeinert** [pm2-hive/pm2-logrotate#85]
TypeError: WATCHED_FILES.includes is not a function
        at proceed_file (/home/michael/.pm2/node_modules/pm2-logrotate/app.js:159:22)
        at null._repeat (/home/michael/.pm2/node_modules/pm2-logrotate/app.js:212:5)
        at wrapper [as _onTimeout] (timers.js:276:11)
        at Timer.listOnTimeout (timers.js:93:15)

 Describing process with id 2 - name pm2-logrotate

    │ status            │ online                                       │
    │ name              │ pm2-logrotate                                │
    │ restarts          │ 3463                                         │
    │ uptime            │ 25s                                          │
    │ script path       │ /home/michael/.pm2/node_modules/pm2-logrotate/app.js │
    │ script args       │ N/A                                          │
    │ error log path    │ /home/michael/.pm2/logs/pm2-logrotate-error-2.log    │
    │ out log path      │ /home/michael/.pm2/logs/pm2-logrotate-out-2.log      │
    │ pid path          │ /home/michael/.pm2/pids/pm2-logrotate-2.pid          │
    │ interpreter       │ node                                         │
    │ interpreter args  │ N/A                                          │
    │ script id         │ 2                                            │
    │ exec cwd          │ /home/michael/.pm2/node_modules/pm2-logrotate        │
    │ exec mode         │ fork_mode                                    │
    │ node.js version   │ 5.2.0                                        │
    │ watch & reload    │ ✘                                            │
    │ unstable restarts │ 0                                            │
    │ created at        │ 2017-12-05T09:54:30.718Z                     │

Process configuration

    │ workerInterval │ 30                  │
    │ rotateModule   │ true                │
    │ rotateInterval │ 0 0 * * *           │
    │ retain         │ all                 │
    │ max_size       │ 10M                 │
    │ dateFormat     │ YYYY-MM-DD_HH-mm-ss │
    │ compress       │ false               │

 Code metrics value

    │ Loop delay       │ 0.37ms  │
    │ Global logs size │ 1.22 MB │
    │ Files count      │ 6       │

What I did wrong ?

**Comment by vmarchaud** [comment]
`node.js version   │ 5.2.0  ` You should try with a newer versions of NodeJS. This one isn't supported.

**Comment by mmeinert** [comment]
I see... I'm afraid of updating it because apps are in production and I didn't code them.
Would an "old" version of pm2-logrotate runs on 5.2.0 ? 
Thank you

**Comment by cs520** [comment]
Also seeing this issue (TypeError: WATCHED_FILES.includes is not a function).

**Comment by therightstuff** [comment]
I'm getting this on 9.4.0

**Comment by imjeffparedes** [comment]
So thats why watch don't work even if it is enabled

**Comment by ronaldho** [comment]
@therightstuff I THOUGHT I had the same problem on 7.1.0... BUT, if you run pm2 describe `pm2-logrotate` and see which version pm2 is actually using, it was using 4.2.0

Turns out, theres a second copy of nodejs on the system (I found under `which nodejs` – which is different than the NVM version I installed under `which node`)

After uninstalling the extra NodeJS package, the crash went away

**Comment by dskrvk** [comment]
I have Node 4.8.7 and ended up downgrading the module to 2.2.0 :-(

**Comment by JeanCarlosChavarriaHughes** [comment]
Any method to disable or stopping pm2-logrotate  while the issue is fixed? I got the same problem as @mmeinert  , my apps are in production and I cannot fix the issue while they are using apps.

**Comment by rmela** [comment]
A fix made it to the development branch but has yet to be merged onto master and packaged for distribution.

**Comment by MikeMiller3** [comment]
pm2 uninstall pm2-logrotate
pm2 install pm2-logrotate@2.2
