### ISSUE TITLE
this._interpretError is not a function

### ISSUE THREAD

**Issue by wirwolf** [pm2-hive/pm2-logrotate#86]
Sometimes i see this error in log 
```
TypeError: this._interpretError is not a function
    at Notify.notify (/home/user/.pm2/node_modules/pmx/lib/notify.js:112:22)
    at emitOne (events.js:115:13)
    at Gzip.emit (events.js:210:7)
    at done (_stream_transform.js:205:19)
    at _flush (_stream_transform.js:138:7)
    at Gzip._transform (zlib.js:369:12)
    at Gzip._flush (zlib.js:301:8)
    at Gzip.prefinish (_stream_transform.js:137:10)
    at emitNone (events.js:105:13)
    at Gzip.emit (events.js:207:7)
```
```
┌──────────────────┬─────────┬────────────┬────────┬─────────┬─────┬─────────────┬──────────┐
│ Module           │ version │ target PID │ status │ restart │ cpu │ memory      │ user     │
├──────────────────┼─────────┼────────────┼────────┼─────────┼─────┼─────────────┼──────────┤
│ pm2-logrotate    │ 2.2.3   │ N/A        │ online │ 161     │ 0%  │ 49.234 MB   │   user   │
│ pm2-mysql        │ 1.0.0   │ N/A        │ online │ 1       │ 0%  │ 0 B         │   user   │
│ pm2-server-monit │ 2.5.1   │ N/A        │ online │ 1       │ 0%  │ 47.902 MB   │   user   │
└──────────────────┴─────────┴────────────┴────────┴─────────┴─────┴─────────────┴──────────┘

```

**Comment by vmarchaud** [comment]
You should try with the latest version (2.4.0), it has been fixed : `pm2 install pm2-logrotate`
